name: user_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  authentication_client:
    path: ../authentication_client/authentication_client
  equatable: ^2.0.5
  rxdart: ^0.27.7
#  storage:
#    path: ../storage/storage
#  yandex_food_api:
#    path: ../../api



dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
