name: multi_vendor_food_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  # custom dependencies:
  app_ui:
    path: packages/app_ui
  form_fields:
    path: packages/form_fields
  firebase_authentication_client:
    path: packages/authentication_client/firebase_authentication_client

  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter



  flutter_dotenv: ^5.1.0
  animations: ^2.0.11
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - .env

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
